name: ðŸš€ Deploy to Somee via FTP

on:
  push:
    branches:
      - main  # hoáº·c branch báº¡n muá»‘n deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # ThÆ° má»¥c báº¡n build ra (hoáº·c ./ náº¿u upload toÃ n bá»™)
          server-dir: /www.trinhnhatminhDH52201066.somee.com      # ThÆ° má»¥c gá»‘c trÃªn server
          protocol: ftp
          port: 21
          log-level: verbose
          timeout: 180000 
